#! /usr/bin/env bash

# install modules
(cd pi_wall_project/common/frontend && npm install --production)
(cd pi_wall_project/weather/frontend && npm install --production)
(cd pi_wall_project/bus/frontend && npm install --production)
(cd pi_wall_project/wifi/frontend && npm install --production)

# build apps
(cd pi_wall_project/common/frontend && npm run build)
(cd pi_wall_project/weather/frontend && npm run build)
(cd pi_wall_project/bus/frontend && npm run build)
(cd pi_wall_project/wifi/frontend && npm run build)
