#! /usr/bin/env bash

for frontend in $(find . -name frontend)
do
  echo "INSTALLING: $frontend"
  (cd $frontend && npm install)
  echo "BUILDING: $frontend"
  (cd $frontend && npm run build)
done
cd pi_wall_project && pipenv run python manage.py collectstatic
