#! /usr/bin/env bash

zip staged.zip $(git ls-files)
echo Building docker container
sudo docker-compose run app pi_wall_project/manage.py collectstatic --no-input
sudo docker-compose up --build -d
rm staged.zip
