#! /bin/sh

tmux has-session -t pi-wall-project
if [ $? != 0 ]
then
    tmux new-session -s pi-wall-project -n Server -d

    # create moar windows
    tmux new-window -t pi-wall-project:1 -n Client
    tmux new-window -t pi-wall-project:2 -n Test
    tmux new-window -t pi-wall-project:3 -n Zsh

    # run the server in the first window
    tmux send-keys -t pi-wall-project:0.0 'cd ~/dev/pi-wall-project && yarn run server' C-m

    # run the client in the second window
    tmux send-keys -t pi-wall-project:1.0 'cd ~/dev/pi-wall-project && yarn start' C-m

    # run the tests in the third window
    tmux send-keys -t pi-wall-project:2.0 'cd ~/dev/pi-wall-project && yarn run test' C-m

    # just get to the proper path in the last window
    tmux send-keys -t pi-wall-project:3.0 'cd ~/dev/pi-wall-project' C-m

    # select the server window and pane
    tmux select-window -t pi-wall-project:0.0
fi
tmux attach -t pi-wall-project
