version: '3'

services:
  app:
    build: .
    volumes:
      - .:/code
      - static_volume:/srv/www/pi-wall-project/static/
    networks:
      - nginx_network

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/srv/www/pi-wall-project/static/
    depends_on:  # <-- wait for app to be "ready" before starting this service
      - app
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
