version: '2'
services:
    web:
        build:
            context: .
            args:
                OPEN_WEATHER_API: "${OPEN_WEATHER_API}"
        entrypoint: npm start
        ports:
            - "80:3000"

